name: Build and Release LaTeX PDF of CV

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: compile-and-upload-as-artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Generate Languages Latex Version
        run: |
          python language-pre-processor.py --language english --file index --output-file-name index.en.tex
          python language-pre-processor.py --language french --file index --output-file-name index.fr.tex

      - name: Build Latex Documents
        uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: |
            index.en.tex
            index.fr.tex
          latexmk_use_xelatex: true

      - name: Upload CV PDFs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cvs
          path: |
            cv.en.pdf
            cv.fr.pdf

  release:
    name: Create GitHub release with CVs PDF
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download CV PDF
        uses: actions/download-artifact@v3
        with:
          name: cvs

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cv.en.pdf
            cv.fr.pdf
          body: This release contains the latest compiled versions of the CV.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
