name: Build and Release LaTeX PDF of CV

on:
  push:
    tags:
      - "v*" # This triggers the workflow only for tags starting with "v"

permissions:
  contents: write # Allow the action to create a release

jobs:
  build:
    name: Compile to PDF and Upload as Artifact
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up LaTeX
      - name: Set up LaTeX
        uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: index.tex
          latexmk_use_xelatex:
            true # Specify xelatex as the LaTeX engine


            # Step 3: Rename the compiled PDF
      - name: Rename PDF
        run: mv index.pdf cv.pdf

      # Step 3: Upload compiled PDF as an artifact
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: cv_pdf
          path: cv.pdf

  release:
    name: Create GitHub release with CV PDF
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Download compiled PDF from previous job
      - name: Download PDF
        uses: actions/download-artifact@v3
        with:
          name: cv_pdf

      # Step 3: Create GitHub release
      - name: Generate Release Notes
        id: release_notes
        uses: actions/github-script@v6
        with:
          script: |
            const { execSync } = require('child_process');

            const commits = execSync('git log -1 --pretty=format:"%s"').toString().trim();
            return `This release contains the latest compiled version of the CV.\n\n- ${commits}`;

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: cv.pdf
          body: ${{ steps.release_notes.outputs.result }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
