name: Build and Release LaTeX PDF of CV

# NOTE: This triggers the workflow only for tags starting with "v"

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: compile-and-upload-as-artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy LaTeX source files
        run: |
          cp index.tex cv-with-motivations.tex
          cp index.tex cv-without-motivations.tex

      - name: Comment out motivations rubric
        run: |
          sed -i 's/\\makerubric{motivations}/%\\makerubric{motivations}/' cv-without-motivations.tex
          cp index.tex index_without_motivations.tex

      - name: Build Latex Documents
        uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: |
            cv-with-motivations.tex
            cv-without-motivations.tex
          latexmk_use_xelatex: true

      - name: Upload CV PDFs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cvs
          path: |
            cv-with-motivations.pdf
            cv-without-motivations.pdf

  release:
    name: Create GitHub release with CVs PDF
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download CV PDF
        uses: actions/download-artifact@v3
        with:
          name: cvs

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cv-with-motivations.pdf
            cv-without-motivations.pdf
          body: This release contains the latest compiled versions of the CV.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
